name: Run Test

on: [push, pull_request]

permissions:
    contents: read
    packages: write

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.13.7"
            - name: Install dependencies
              run: pip install -r requirements-dev.txt
            - name: Check linting
              run: ruff check .
            - name: Run test
              run: pytest
            
              


            
            